### ISSUE TITLE
建议设计符合Unity

### ISSUE THREAD

**Issue by cnSchwarzer** [871041532/zstring#2]
using(zstring.Block()){ ... }并不适合游戏结构，建议以每帧为一个block进行回收再利用，否则UGUI或者TextMeshPro会造成文字显示不正确

**Comment by 871041532** [comment]
哎？ 显示不正确的具体表现是什么。 怎么复现一下？

**Comment by 871041532** [comment]
之前项目用的FairyGUI没有这个问题。
UGUI异常原因请看这位老兄的帖子 https://blog.csdn.net/cyf649669121/article/details/83414385 

转载部分内容：
【**Text.text被修改后，Unity并没有立即修改文本显示（感觉上是这样）。虽然看了源码也没发现有什么地方不对，但实际上就是这种效果。
后来苦思冥想想不通，用了个很弱智的方法来解决：
在每一次对Text进行赋值后，同时更改Text的颜色。其颜色用2个颜色交替，一个是原来的颜色，另一个是比原来的颜色其透明度略低0.005的颜色（表现上基本看不出差别）；或者修改文本框的长宽。
至于为什么，只能说能力有限了……**】
--------------------- 
作者：魔术师Dix 
来源：CSDN 
原文：https://blog.csdn.net/cyf649669121/article/details/83414385 
版权声明：本文为博主原创文章，转载请附上博文链接！

**Comment by ZeroUltra** [comment]
我猜测是因为用zString没有让text引起网格重建,所以文字没法实时刷新出来, 而改变颜色,修改长宽或者Text组建上的其他属性都会引起网格重建,从而触发重建,这时候就会实时显示出来了,或者可以直接用Text的这个方法 text.OnRebuildRequested();

**Comment by ZeroUltra** [comment]
> 之前项目用的FairyGUI没有这个问题
> .UGUI异常原因请看这位老兄的帖子https://blog.csdn.net/cyf649669121/article/details/83414385
> 
> ## 转载部分内容：
> 【**Text.text被修改后，Unity并没有立即修改文本显示（感觉上是这样）。虽然看了源码也没发现有什么地方不对，但实际上就是这种效果。 后来苦思冥想想不通，用了个很弱智的方法来解决： 。在每一次对文本进行赋值后，同时更改文本的颜色其颜色用2个颜色交替，一个是原来的颜色，另一个是比原来的颜色其透明度略低0.005的颜色（表现上基本看不出差别）;修改或者字幕：框的长宽 至于为什么，只能说能力有限了......**】
> 作者：魔术师Dix 
> 来源：CSDN 
> 原文：[https](https://blog.csdn.net/cyf649669121/article/details/83414385)：//blog.csdn.net/cyf649669121/article/details/83414385 
> 版权声明：本文为博主原创文章，转载请附上博文链接！

我猜测是因为用zString没有让文引引网格重建，所以文字没法实时刷新出来，而改变颜色，修改长宽或者文字组建上的其他属性都会引起网格重建，从而触发重建，这时候就会实时显示出来了，或者可以直接用Text的这个方法text.OnRebuildRequested（）;

**Comment by 871041532** [comment]
新版本已解决
