### ISSUE TITLE
大佬，打包Android IL2CPP会有报错

### ISSUE THREAD

**Issue by TrustTJMGmail** [871041532/zstring#4]
运行环境：Unity2018.3.9f1
Scripting Runtime Version:.NET 4.x Equivalent

部分Log:

Failed running C:\Program Files\Unity2018.3.9f1\Editor\Data\il2cpp/build/il2cpp.exe --convert-to-cpp --emit-null-checks --enable-array-bounds-check --dotnetprofile="unityaot" --compile-cpp --libil2cpp-static --platform="Android" --architecture="ARM64" --configuration="Release" --outputpath="F:\My\Unity\Project\TrustFramework\client\Unity\TrustFramework\Temp\StagingArea\assets\bin\Data\Native\arm64-v8a\libil2cpp.so" --cachedirectory="F:\My\Unity\Project\TrustFramework\client\Unity\TrustFramework\Assets\..\Library\il2cpp_android_arm64-v8a/il2cpp_cache" --additional-include-directories="C:\Program Files\Unity2018.3.9f1\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\bdwgc/include" --additional-include-directories="C:\Program Files\Unity2018.3.9f1\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\libil2cpp/include" --tool-chain-path="E:/Workspace/Android/android-ndk-r16b" --map-file-parser="C:\Program Files\Unity2018.3.9f1\Editor\Data\Tools\MapFileParser\MapFileParser.exe" --directory="F:\My\Unity\Project\TrustFramework\client\Unity\TrustFramework\Temp\StagingArea\assets\bin\Data\Managed" --generatedcppdir="F:\My\Unity\Project\TrustFramework\client\Unity\TrustFramework\Temp\StagingArea\Il2Cpp\il2cppOutput" 

stdout:
Building libil2cpp.so with AndroidToolChain
	Output directory: F:\My\Unity\Project\TrustFramework\client\Unity\TrustFramework\Temp\StagingArea\assets\bin\Data\Native\arm64-v8a
	Cache directory: F:\My\Unity\Project\TrustFramework\client\Unity\TrustFramework\Library\il2cpp_android_arm64-v8a\il2cpp_cache
il2cpp.exe didn't catch exception: Unity.IL2CPP.Building.BuilderFailedException: F:\My\Unity\Project\TrustFramework\client\Unity\TrustFramework\Temp\StagingArea\Il2Cpp\il2cppOutput\Bulk_Assembly-CSharp_5.cpp:31352:5: error: use of undeclared identifier 'Byte8192_t859D083D49C0C1A52B1796E8E2EFFA0BF9A466BA'
                *(Byte8192_t859D083D49C0C1A52B1796E8E2EFFA0BF9A466BA *)L_4 = (*(Byte8192_t859D083D49C0C1A52B1796E8E2EFFA0BF9A466BA *)L_5);
                  ^
F:\My\Unity\Project\TrustFramework\client\Unity\TrustFramework\Temp\StagingArea\Il2Cpp\il2cppOutput\Bulk_Assembly-CSharp_5.cpp:31352:57: error: expected expression
                *(Byte8192_t859D083D49C0C1A52B1796E8E2EFFA0BF9A466BA *)L_4 = (*(Byte8192_t859D083D49C0C1A52B1796E8E2EFFA0BF9A466BA *)L_5);
                                                                      ^
F:\My\Unity\Project\TrustFramework\client\Unity\TrustFramework\Temp\StagingArea\Il2Cpp\il2cppOutput\Bulk_Assembly-CSharp_5.cpp:31389:5: error: use of undeclared identifier 'Byte4096_tBD6CE6ABF553314AC5B27C97D2F9692C61365E5C'
                *(Byte4096_tBD6CE6ABF553314AC5B27C97D2F9692C61365E5C *)L_13 = (*(Byte4096_tBD6CE6ABF553314AC5B27C97D2F9692C61365E5C *)L_14);
                  ^
F:\My\Unity\Project\TrustFramework\client\Unity\TrustFramework\Temp\StagingArea\Il2Cpp\il2cppOutput\Bulk_Assembly-CSharp_5.cpp:31389:57: error: expected expression
                *(Byte4096_tBD6CE6ABF553314AC5B27C97D2F9692C61365E5C *)L_13 = (*(Byte4096_tBD6CE6ABF553314AC5B27C97D2F9692C61365E5C *)L_14);
                                                                      ^
F:\My\Unity\Project\TrustFramework\client\Unity\TrustFramework\Temp\StagingArea\Il2Cpp\il2cppOutput\Bulk_Assembly-CSharp_5.cpp:31416:5: error: use of undeclared identifier 'Byte2048_t3BCFE5D5DF98ECC0B13477DFC6128A0B6C839ABE'
                *(Byte2048_t3BCFE5D5DF98ECC0B13477DFC6128A0B6C839ABE *)L_20 = (*(Byte2048_t3BCFE5D5DF98ECC0B13477DFC6128A0B6C839ABE *)L_21);
                  ^
F:\My\Unity\Project\TrustFramework\client\Unity\TrustFramework\Temp\StagingArea\Il2Cpp\il2cppOutput\Bulk_Assembly-CSharp_5.cpp:31416:57: error: expected expression
                *(Byte2048_t3BCFE5D5DF98ECC0B13477DFC6128A0B6C839ABE *)L_20 = (*(Byte2048_t3BCFE5D5DF98ECC0B13477DFC6128A0B6C839ABE *)L_21);
                                                                      ^
F:\My\Unity\Project\TrustFramework\client\Unity\TrustFramework\Temp\StagingArea\Il2Cpp\il2cppOutput\Bulk_Assembly-CSharp_5.cpp:31443:5: error: use of undeclared identifier 'Byte1024_t0BBBB4EC3D1A9026D36FE8A837171263B47F8301'
                *(Byte1024_t0BBBB4EC3D1A9026D36FE8A837171263B47F8301 *)L_27 = (*(Byte1024_t0BBBB4EC3D1A9026D36FE8A837171263B47F8301 *)L_28);
                  ^
F:\My\Unity\Project\TrustFramework\client\Unity\TrustFramework\Temp\StagingArea\Il2Cpp\il2cppOutput\Bulk_Assembly-CSharp_5.cpp:31443:57: error: expected expression
                *(Byte1024_t0BBBB4EC3D1A9026D36FE8A837171263B47F8301 *)L_27 = (*(Byte1024_t0BBBB4EC3D1A9026D36FE8A837171263B47F8301 *)L_28);
                                                                      ^
F:\My\Unity\Project\TrustFramework\client\Unity\TrustFramework\Temp\StagingArea\Il2Cpp\il2cppOutput\Bulk_Assembly-CSharp_5.cpp:31470:5: error: use of undeclared identifier 'Byte512_t4F4640E213B59685AD82B74250D784210BC5B99C'
                *(Byte512_t4F4640E213B59685AD82B74250D784210BC5B99C *)L_34 = (*(Byte512_t4F4640E213B59685AD82B74250D784210BC5B99C *)L_35);
                  ^
F:\My\Unity\Project\TrustFramework\client\Unity\TrustFramework\Temp\StagingArea\Il2Cpp\il2cppOutput\Bulk_Assembly-CSharp_5.cpp:31470:56: error: expected expression
                *(Byte512_t4F4640E213B59685AD82B74250D784210BC5B99C *)L_34 = (*(Byte512_t4F4640E213B59685AD82B74250D784210BC5B99C *)L_35);
                                                                     ^
F:\My\Unity\Project\TrustFramework\client\Unity\TrustFramework\Temp\StagingArea\Il2Cpp\il2cppOutput\Bulk_Assembly-CSharp_5.cpp:31497:5: error: use of undeclared identifier 'Byte256_t1348DFC1B1E3AE428A9E58A8E5637B8EA3782C69'
                *(Byte256_t1348DFC1B1E3AE428A9E58A8E5637B8EA3782C69 *)L_41 = (*(Byte256_t1348DFC1B1E3AE428A9E58A8E5637B8EA3782C69 *)L_42);
                  ^
F:\My\Unity\Project\TrustFramework\client\Unity\TrustFramework\Temp\StagingArea\Il2Cpp\il2cppOutput\Bulk_Assembly-CSharp_5.cpp:31497:56: error: expected expression
                *(Byte256_t1348DFC1B1E3AE428A9E58A8E5637B8EA3782C69 *)L_41 = (*(Byte256_t1348DFC1B1E3AE428A9E58A8E5637B8EA3782C69 *)L_42);
                                                                     ^
F:\My\Unity\Project\TrustFramework\client\Unity\TrustFramework\Temp\StagingArea\Il2Cpp\il2cppOutput\Bulk_Assembly-CSharp_5.cpp:31524:5: error: use of undeclared identifier 'Byte128_t47693D60AA2F2BD06AB8D0A40E0230876B91E9E4'
                *(Byte128_t47693D60AA2F2BD06AB8D0A40E0230876B91E9E4 *)L_48 = (*(Byte128_t47693D60AA2F2BD06AB8D0A40E0230876B91E9E4 *)L_49);
                  ^
F:\My\Unity\Project\TrustFramework\client\Unity\TrustFramework\Temp\StagingArea\Il2Cpp\il2cppOutput\Bulk_Assembly-CSharp_5.cpp:31524:56: error: expected expression
                *(Byte128_t47693D60AA2F2BD06AB8D0A40E0230876B91E9E4 *)L_48 = (*(Byte128_t47693D60AA2F2BD06AB8D0A40E0230876B91E9E4 *)L_49);
                                                                     ^
F:\My\Unity\Project\TrustFramework\client\Unity\TrustFramework\Temp\StagingArea\Il2Cpp\il2cppOutput\Bulk_Assembly-CSharp_5.cpp:31551:5: error: use of undeclared identifier 'Byte64_t94D3F74EF7C4D4E51931CD696F4678EC94FDFE16'
                *(Byte64_t94D3F74EF7C4D4E51931CD696F4678EC94FDFE16 *)L_55 = (*(Byte64_t94D3F74EF7C4D4E51931CD696F4678EC94FDFE16 *)L_56);
                  ^
F:\My\Unity\Project\TrustFramework\client\Unity\TrustFramework\Temp\StagingArea\Il2Cpp\il2cppOutput\Bulk_Assembly-CSharp_5.cpp:31551:55: error: expected expression
                *(Byte64_t94D3F74EF7C4D4E51931CD696F4678EC94FDFE16 *)L_55 = (*(Byte64_t94D3F74EF7C4D4E51931CD696F4678EC94FDFE16 *)L_56);
                                                                    ^
F:\My\Unity\Project\TrustFramework\client\Unity\TrustFramework\Temp\StagingArea\Il2Cpp\il2cppOutput\Bulk_Assembly-CSharp_5.cpp:31578:5: error: use of undeclared identifier 'Byte32_t75FF90FC74499EFA15159627ADBA12242AC192D0'
                *(Byte32_t75FF90FC74499EFA15159627ADBA12242AC192D0 *)L_62 = (*(Byte32_t75FF90FC74499EFA15159627ADBA12242AC192D0 *)L_63);
                  ^
F:\My\Unity\Project\TrustFramework\client\Unity\TrustFramework\Temp\StagingArea\Il2Cpp\il2cppOutput\Bulk_Assembly-CSharp_5.cpp:31578:55: error: expected expression
                *(Byte32_t75FF90FC74499EFA15159627ADBA12242AC192D0 *)L_62 = (*(Byte32_t75FF90FC74499EFA15159627ADBA12242AC192D0 *)L_63);
                                                                    ^
F:\My\Unity\Project\TrustFramework\client\Unity\TrustFramework\Temp\StagingArea\Il2Cpp\il2cppOutput\Bulk_Assembly-CSharp_5.cpp:31605:5: error: use of undeclared identifier 'Byte16_t8C0FAC8165912C33164D9719DA6BFE12D06DFDEF'
                *(Byte16_t8C0FAC8165912C33164D9719DA6BFE12D06DFDEF *)L_69 = (*(Byte16_t8C0FAC8165912C33164D9719DA6BFE12D06DFDEF *)L_70);
                  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.

Invocation was: Executable: "E:\Workspace\Android\android-ndk-r16b\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++"
Arguments: -DNET_4_0 -DUNITY_AOT -DGC_NOT_DLL -DRUNTIME_IL2CPP -DLINUX -DANDROID -DPLATFORM_ANDROID -D__linux__ -D__STDC_FORMAT_MACROS -DTARGET_ARM64 -I"C:\Program Files\Unity2018.3.9f1\Editor\Data\PlaybackEngines\AndroidPlayer\Tools\bdwgc\include" -I"C:\Program Files\Unity2018.3.9f1\Editor\Data\PlaybackEngines\AndroidPlayer\Tools\libil2cpp\include" -I"C:\Program Files\Unity2018.3.9f1\Editor\Data\il2cpp\libil2cpp" -I"C:\Program Files\Unity2018.3.9f1\Editor\Data\il2cpp\external\boehmgc\include" -I"F:\My\Unity\Project\TrustFramework\client\Unity\TrustFramework\Temp\StagingArea\Il2Cpp\il2cppOutput" -I"." -I"E:\Workspace\Android\android-ndk-r16b\sources\cxx-stl\gnu-libstdc++\4.9\include" -I"E:\Workspace\Android\android-ndk-r16b\sources\cxx-stl\gnu-libstdc++\4.9\include\backward" -I"E:\Workspace\Android\android-ndk-r16b\sources\cxx-stl\gnu-libstdc++\4.9\libs\arm64-v8a\include" -c -g -DNDEBUG -funwind-tables -fno-limit-debug-info -fdata-sections -ffunction-sections -Wa,--noexecstack -fno-rtti -std=c++98 -fno-strict-aliasing -fvisibility=hidden -fvisibility-inlines-hidden -fno-strict-overflow -fPIC -Os --sysroot "E:\Workspace\Android\android-ndk-r16b\sysroot" -gcc-toolchain "E:\Workspace\Android\android-ndk-r16b\toolchains\aarch64-linux-android-4.9\prebuilt\windows-x86_64" -target aarch64-none-linux-android -isystem "E:\Workspace\Android\android-ndk-r16b\sysroot\usr\include\aarch64-linux-android" -D__ANDROID_API__=21 -march=armv8-a -Wno-unused-value "F:\My\Unity\Project\TrustFramework\client\Unity\TrustFramework\Temp\StagingArea\Il2Cpp\il2cppOutput\Bulk_Assembly-CSharp_5.cpp" -o "F:/My/Unity/Project/TrustFramework/client/Unity/TrustFramework/Library/il2cpp_android_arm64-v8a/il2cpp_cache/1084D6449E9D3B1F950C3DF201B25368.o"

   �� Unity.IL2CPP.Building.CppProgramBuilder.BuildAllCppFiles(IEnumerable`1 sourceFilesToCompile, IBuildStatisticsCollector statisticsCollector)
   �� Unity.IL2CPP.Building.CppProgramBuilder.Build(IBuildStatistics& statistics)
   �� il2cpp.Program.DoRun(String[] args)
   �� il2cpp.Program.Run(String[] args)
   �� il2cpp.Program.Main(String[] args)
stderr:

δ��������쳣:  Unity.IL2CPP.Building.BuilderFailedException: F:\My\Unity\Project\TrustFramework\client\Unity\TrustFramework\Temp\StagingArea\Il2Cpp\il2cppOutput\Bulk_Assembly-CSharp_5.cpp:31352:5: error: use of undeclared identifier 'Byte8192_t859D083D49C0C1A52B1796E8E2EFFA0BF9A466BA'
                *(Byte8192_t859D083D49C0C1A52B1796E8E2EFFA0BF9A466BA *)L_4 = (*(Byte8192_t859D083D49C0C1A52B1796E8E2EFFA0BF9A466BA *)L_5);
                  ^
F:\My\Unity\Project\TrustFramework\client\Unity\TrustFramework\Temp\StagingArea\Il2Cpp\il2cppOutput\Bulk_Assembly-CSharp_5.cpp:31352:57: error: expected expression
                *(Byte8192_t859D083D49C0C1A52B1796E8E2EFFA0BF9A466BA *)L_4 = (*(Byte8192_t859D083D49C0C1A52B1796E8E2EFFA0BF9A466BA *)L_5);
                                                                      ^
F:\My\Unity\Project\TrustFramework\client\Unity\TrustFramework\Temp\StagingArea\Il2Cpp\il2cppOutput\Bulk_Assembly-CSharp_5.cpp:31389:5: error: use of undeclared identifier 'Byte4096_tBD6CE6ABF553314AC5B27C97D2F9692C61365E5C'
                *(Byte4096_tBD6CE6ABF553314AC5B27C97D2F9692C61365E5C *)L_13 = (*(Byte4096_tBD6CE6ABF553314AC5B27C97D2F9692C61365E5C *)L_14);
                  ^
F:\My\Unity\Project\TrustFramework\client\Unity\TrustFramework\Temp\StagingArea\Il2Cpp\il2cppOutput\Bulk_Assembly-CSharp_5.cpp:31389:57: error: expected expression
                *(Byte4096_tBD6CE6ABF553314AC5B27C97D2F9692C61365E5C *)L_13 = (*(Byte4096_tBD6CE6ABF553314AC5B27C97D2F9692C61365E5C *)L_14);
                                                                      ^
F:\My\Unity\Project\TrustFramework\client\Unity\TrustFramework\Temp\StagingArea\Il2Cpp\il2cppOutput\Bulk_Assembly-CSharp_5.cpp:31416:5: error: use of undeclared identifier 'Byte2048_t3BCFE5D5DF98ECC0B13477DFC6128A0B6C839ABE'
                *(Byte2048_t3BCFE5D5DF98ECC0B13477DFC6128A0B6C839ABE *)L_20 = (*(Byte2048_t3BCFE5D5DF98ECC0B13477DFC6128A0B6C839ABE *)L_21);
                  ^
F:\My\Unity\Project\TrustFramework\client\Unity\TrustFramework\Temp\StagingArea\Il2Cpp\il2cppOutput\Bulk_Assembly-CSharp_5.cpp:31416:57: error: expected expression
                *(Byte2048_t3BCFE5D5DF98ECC0B13477DFC6128A0B6C839ABE *)L_20 = (*(Byte2048_t3BCFE5D5DF98ECC0B13477DFC6128A0B6C839ABE *)L_21);
                                                                      ^
F:\My\Unity\Project\TrustFramework\client\Unity\TrustFramework\Temp\StagingArea\Il2Cpp\il2cppOutput\Bulk_Assembly-CSharp_5.cpp:31443:5: error: use of undeclared identifier 'Byte1024_t0BBBB4EC3D1A9026D36FE8A837171263B47F8301'
                *(Byte1024_t0BBBB4EC3D1A9026D36FE8A837171263B47F8301 *)L_27 = (*(Byte1024_t0BBBB4EC3D1A9026D36FE8A837171263B47F8301 *)L_28);
                  ^
F:\My\Unity\Project\TrustFramework\client\Unity\TrustFramework\Temp\StagingArea\Il2Cpp\il2cppOutput\Bulk_Assembly-CSharp_5.cpp:31443:57: error: expected expression
                *(Byte1024_t0BBBB4EC3D1A9026D36FE8A837171263B47F8301 *)L_27 = (*(Byte1024_t0BBBB4EC3D1A9026D36FE8A837171263B47F8301 *)L_28);
                                                                      ^
F:\My\Unity\Project\TrustFramework\client\Unity\TrustFramework\Temp\StagingArea\Il2Cpp\il2cppOutput\Bulk_Assembly-CSharp_5.cpp:31470:5: error: use of undeclared identifier 'Byte512_t4F4640E213B59685AD82B74250D784210BC5B99C'
                *(Byte512_t4F4640E213B59685AD82B74250D784210BC5B99C *)L_34 = (*(Byte512_t4F4640E213B59685AD82B74250D784210BC5B99C *)L_35);
                  ^
F:\My\Unity\Project\TrustFramework\client\Unity\TrustFramework\Temp\StagingArea\Il2Cpp\il2cppOutput\Bulk_Assembly-CSharp_5.cpp:31470:56: error: expected expression
                *(Byte512_t4F4640E213B59685AD82B74250D784210BC5B99C *)L_34 = (*(Byte512_t4F4640E213B59685AD82B74250D784210BC5B99C *)L_35);
                                                                     ^
F:\My\Unity\Project\TrustFramework\client\Unity\TrustFramework\Temp\StagingArea\Il2Cpp\il2cppOutput\Bulk_Assembly-CSharp_5.cpp:31497:5: error: use of undeclared identifier 'Byte256_t1348DFC1B1E3AE428A9E58A8E5637B8EA3782C69'
                *(Byte256_t1348DFC1B1E3AE428A9E58A8E5637B8EA3782C69 *)L_41 = (*(Byte256_t1348DFC1B1E3AE428A9E58A8E5637B8EA3782C69 *)L_42);
                  ^
F:\My\Unity\Project\TrustFramework\client\Unity\TrustFramework\Temp\StagingArea\Il2Cpp\il2cppOutput\Bulk_Assembly-CSharp_5.cpp:31497:56: error: expected expression
                *(Byte256_t1348DFC1B1E3AE428A9E58A8E5637B8EA3782C69 *)L_41 = (*(Byte256_t1348DFC1B1E3AE428A9E58A8E5637B8EA3782C69 *)L_42);
                                                                     ^
F:\My\Unity\Project\TrustFramework\client\Unity\TrustFramework\Temp\StagingArea\Il2Cpp\il2cppOutput\Bulk_Assembly-CSharp_5.cpp:31524:5: error: use of undeclared identifier 'Byte128_t47693D60AA2F2BD06AB8D0A40E0230876B91E9E4'
                *(Byte128_t47693D60AA2F2BD06AB8D0A40E0230876B91E9E4 *)L_48 = (*(Byte128_t47693D60AA2F2BD06AB8D0A40E0230876B91E9E4 *)L_49);
                  ^
F:\My\Unity<message truncated>

**Comment by 871041532** [comment]
看样子是FULL AOT编译不识别结构体，把zstring.cs 中 Bytex系列结构体定义放到zstring类内部，或者放到plugins目录下试试
