### ISSUE TITLE
Unity 设置两个文本 不同字符串， 有可能设置错误

### ISSUE THREAD

**Issue by ZeroChiLi** [871041532/zstring#6]
Unity 设置两个文本 不同字符串， 有可能设置错误：
第一个文本字符串设置“abc”  第二个文本设置“123” （每次设置都在一个block 且 设置完都改变颜色以重置网格显示）
打印时，两个都输出正确的值，
但是会出现 第二个文本显示了"abc"的错误，第二个文本在组件上显示第一个文本的字符串"abc"
即设置给第一个文本的字符串"abc"，同时赋值给了第一个文本和第二个文本，感觉像是第二个文本的字符串被引用住了

**Comment by ZeroChiLi** [comment]
重现方法：
```csharp
using Common;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class test2 : MonoBehaviour
{
    int a = 0;
    public Text textCom;
    public Text textCom2;
    public bool trigger = false;
    Color upColor = new Color(0, 0, 0, 0.001f);

    void Update()
    {
        ++a;
        using (zstring.Block())
        {
            textCom.text = (zstring)a;
            trigger = !trigger;
            textCom.color = trigger ? textCom.color + upColor : textCom.color - upColor;
        }

        if (Time.frameCount % 60 == 0)
        {
            using (zstring.Block())
            {
                textCom2.text = (zstring)a;
                trigger = !trigger;
                textCom2.color = trigger ? textCom2.color + upColor : textCom2.color - upColor;
            }
        }
    }
}
```
观察两个UI文本组件，上面显示的文本内容会完全一样。
---
大概也猜到原因了：`zstring.get(int length)` 这个方法，根据长度获取zstring，估计是第二次获取的时候，指向了同一个引用对象（前面刚用完那个）

**Comment by 871041532** [comment]
update中的zstring.block｛｝只写一个就好啦。  把剩下的逻辑都写到｛｝中。



发自我的小米手机
在 2019年8月3日 下午5:38，ChiLi_Lin <notifications@github.com>写道：

重现方法：

using Common;

using System.Collections;

using System.Collections.Generic;

using UnityEngine;

using UnityEngine.UI;



public class test2 : MonoBehaviour

{

    int a = 0;

    public Text textCom;

    public Text textCom2;

    public bool trigger = false;

    Color upColor = new Color(0, 0, 0, 0.001f);



    void Update()

    {

        ++a;

        using (zstring.Block())

        {

            textCom.text = (zstring)a;

            trigger = !trigger;

            textCom.color = trigger ? textCom.color + upColor : textCom.color - upColor;

        }



        if (Time.frameCount % 60 == 0)

        {

            using (zstring.Block())

            {

                textCom2.text = (zstring)a;

                trigger = !trigger;

                textCom2.color = trigger ? textCom2.color + upColor : textCom2.color - upColor;

            }

        }

    }

}

观察两个UI文本组件，上面显示的文本内容会完全一样。

大概也猜到原因了：zstring.get(int length) 这个方法，根据长度获取zstring，估计是第二次获取的时候，指向了同一个引用对象（前面刚用完那个）

―

**Comment by ZeroChiLi** [comment]
那只是我的演示，实际上是两个地方调用(⊙_⊙)

**Comment by 871041532** [comment]
把两处调用写在一个block里面，或者 .Intern() 一下吧

**Comment by 871041532** [comment]
如果在两个Update里代码不太好合到一处，又不想要 .Intern() 放入常驻缓存一直占用内存空间：
① 如果只是在Update范围内保证字符串正确性。可以考虑将using(){} 语法糖拆成两个，比如 Block.Begin()     Block.End()。 在UI 统一Tick之前调用 Block.Begin()， 在UITick之后调用 Block.End()回收。
② 如果字符串只是需要在一段时间内常驻内存保持正确性。 可以参考.Intern() 加个 .InternVariant() 放入自定义缓存中，在恰当实时机手动clear一下。

**Comment by ZeroChiLi** [comment]
用方法2 动态Intern解决了问题，感谢作者的回复 :laughing:

**Comment by ZeroChiLi** [comment]
还有种方法就是一个组件搞一个block 在修改文本前 一直拿着，要改再Dispose之前的block。
